---
codejail_debian_packages:
  - apparmor-utils
codejail_python_versions:
  - python27
  - python35
  - python36
codejail_sandbox_user: 'sandbox'
codejail_sandbox_group: 'sandbox'
codejail_sandbox_name_base: 'codejail_sandbox'
codejail_sandbox_env: '/home/{{ codejail_sandbox_user }}/{{ codejail_sandbox_name_base }}'
codejail_sandbox_caller: 'ubuntu'
